#include "../inc/Menu.hpp"
agl::Event		 *MenuShare::event;
agl::Text		 *MenuShare::text;
agl::Text		 *MenuShare::smallText;
agl::Rectangle	 *MenuShare::rect;
agl::Circle		 *MenuShare::circ;
agl::Texture	 *MenuShare::border;
agl::Texture	 *MenuShare::blank;
void			 *MenuShare::focusedMenu;
bool			 *MenuShare::leftClick;
FocusableElement *FocusableElement::focusedField;
agl::Shader		 *MenuShare::menuShader;
agl::Shader		 *MenuShare::baseShader;
agl::Camera		 *MenuShare::camera;
